# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - portal-virittamo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://virittamo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_be53bbd699f94aec85a857d52927004d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_16823855e91c49d3a68e3163367d741c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: virittamo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_be53bbd699f94aec85a857d52927004d }}/virittamo/virittamointranet:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portal-virittamo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a05378b76f349f5b6fdaf69f5e0a560 }}
        images: 'virittamo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_be53bbd699f94aec85a857d52927004d }}/virittamo/virittamointranet:${{ github.sha }}'